debug: true

module-manager:
  folders: []
  load-internal-modules: true
  install-pip-requirements: true

entity-discovery:
  active: true
  interval: 30

api-server:
  host: null
  port: 8080

szenes: []

automation: []

items: []
