module-manager:
  folders: []
  load-internal-modules: true
  install-pip-requirements: true

api-server:
  host: null
  port: 8080

api-server:
  headers:
    Allow: GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS
    Access-Control-Request-Method: GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: X-PINGOTHER, Content-Type

szenes: !include szenes.yaml

automation: !include automation.yaml

items: !include items.yaml
