module-manager:
  folders: []
  load-internal-modules: true
  install-pip-requirements: true

http-server:
  host: null
  port: 8080
  # Uncomment to use ssl
  # ssl:
    # key: !path ssl/private_key.pem
    # certificate: !path ssl/certificate.pem

api-server:
  headers:
    Allow: GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS
    Access-Control-Request-Method: GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: X-PINGOTHER, Content-Type

auth:
  providers:
    - type: trusted-clients
      trusted-networks:
        - address: 127.0.0.1
          user: system
        - address: ::1/128
          user: system
    - type: oauth

  login-flows:
    password:
      provider: password
      mfa-modules: totp

szenes: !include szenes.yaml

automation: !include automation.yaml

items: !include items.yaml
